services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: healthclaim-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pass@word1
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  api:
    build: .
    container_name: healthclaim-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=LAPTOP-O543Q9N6;Database=HealthClaimProDB;User Id=sa;Password=Pass@word1;TrustServerCertificate=True;
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver

volumes:
  sqlserver-data: